import Head from "next/head";
// import Image from "next/image";
import Header from "../components/Header/Header";
import Navbar from "../components/Navbar/Navbar";
import Result from "../components/Results/Result";
import Request from "../utils/Request";
export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>hulu2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* Header */}
        <Header />

        {/* Nav */}
        <Navbar />

        {/* Results */}
        <Result results={results} />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const request = await fetch(
    `https://api.themoviedb.org/3${
      Request[genre]?.url || Request.fetchTrending.url
    }`
  ).then((res) => res.json());
  return {
    props: {
      results: request.results,
    },
  };
}
